name: Generate sites and upload ZIP

on:
  push:
    branches:
      - generate-sites

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run generator script
        run: |
          python3 generate_sites.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pinyin_folders_42
          path: pinyin_folders_42.zip
